//user Reducer
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const REGISTER_USER="REGISTER_USER"
export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOADING_USER = "LOADING_USER";
export const REGISTER_FAIL="REGISTER_FAIL"
export const VERIFY_OTP="VERIFY_OTP"
export const FETCH_EMPLOYEE_REQUEST = 'FETCH_EMPLOYEE_REQUEST';
export const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS';
export const FETCH_EMPLOYEE_FAILURE = 'FETCH_EMPLOYEE_FAILURE';
