//user Reducer

export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOADING_USER = "LOADING_USER";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const VERIFY_OTP = "VERIFY_OTP";
export const LOADING_OTP = "LOADING_OTP";
export const VERIFY_OTP_FAIL = "VERIFY_OTP_FAIL";
export const RESEND_OTP = "RESEND_OTP";
export const OTP_FAIL = "OTP_FAIL";
export const OTP_LOADING = "OTP_LOADING";
export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const LOADING_FORGET_PASSWORD = "LOADING_FORGET_PASSWORD";
export const FORGET_PASSWORD_FAIL = "FORGET_PASSWORD_FAIL";
export const RESEND_PASSWORD = "RESEND_PASSWORD";
export const LOADING_RESEND_PASSWORD = "LOADING_RESEND_PASSWORD";
export const RESEND_PASSWORD_FAIL = "RESEND_PASSWORD_FAIL";
